version: "3.3"
services:
  aqueduct:
    container_name: aqueductTest
    build: ./docker/aqueducttest
    ports:
      - "80:8888"
    networks:
      - networks_web_api
  db:
    container_name: postgresTest
    build: ./docker/postgrestest
    volumes:
      - db_data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 65432:5432
    networks:
      - networks_web_api
    command: -p 5432
networks:
  networks_web_api:
    driver: bridge
volumes:
  db_data: {}
    